name: cs109b
channels:
  - jmcmurray
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - altair=4.0.1
  - arviz=0.6.1
  - astor=0.7.1
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - beautifulsoup4=4.8.2
  - blas=1.0
  - bleach=3.1.0
  - bokeh=1.4.0
  - boto=2.49.0
  - boto3=1.11.9
  - botocore=1.14.9
  - bz2file=0.98
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - catalogue=1.0.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - cftime=1.0.4.2
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.2.2
  - colorama=0.4.3
  - cryptography=2.8
  - curl=7.65.3
  - cycler=0.10.0
  - cymem=2.0.3
  - cython-blis=0.4.1
  - cytoolz=0.10.1
  - dash=1.7.0
  - dash-core-components=1.6.0
  - dash-html-components=1.0.2
  - dash-renderer=1.2.2
  - dash-table=4.5.1
  - dask-core=2.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - docutils=0.15.2
  - entrypoints=0.3
  - flask=1.1.1
  - flask-compress=1.4.0
  - freetype=2.10.0
  - future=0.18.2
  - gast=0.2.2
  - gensim=3.8.1
  - google-pasta=0.1.8
  - grpcio=1.23.0
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - holoviews=1.12.7
  - icu=64.2
  - idna=2.8
  - imageio=2.6.1
  - importlib_metadata=1.5.0
  - inflect=4.0.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipytest=0.5.0
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - itsdangerous=1.1.0
  - jaraco.itertools=5.0.0
  - jedi=0.16.0
  - jinja2=2.11.0
  - jmespath=0.9.4
  - joblib=0.14.1
  - jpeg=9c
  - json=0.1.1
  - json5=0.8.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.1
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.65.3
  - libgpuarray=0.7.6
  - liblapack=3.8.0
  - libmklml=2019.0.5
  - libnetcdf=4.7.3
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.17
  - libssh2=1.8.2
  - libtiff=4.1.0
  - llvm-openmp=9.0.1
  - mako=1.1.0
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mistune=0.8.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - more-itertools=8.2.0
  - murmurhash=1.0.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - netcdf4=1.5.3
  - networkx=2.4
  - nltk=3.4.4
  - notebook=6.0.3
  - numpy=1.17.5
  - olefile=0.46
  - openssl=1.1.1d
  - opt_einsum=3.1.0
  - packaging=20.1
  - pandas=0.25.3
  - pandoc=2.9.1.1
  - pandocfilters=1.4.2
  - param=1.9.3
  - parso=0.6.0
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - plac=0.9.6
  - plotly=4.5.0
  - pluggy=0.13.0
  - preshed=3.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - protobuf=3.11.2
  - py=1.8.1
  - pycparser=2.19
  - pygments=2.5.2
  - pygpu=0.7.6
  - pymc3=3.8
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - pyrsistent=0.15.6
  - pysocks=1.7.1
  - pytest=5.3.5
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyviz_comms=0.7.3
  - pywavelets=1.1.1
  - pyyaml=5.3
  - pyzmq=18.1.1
  - qt=5.12.5
  - qtconsole=4.6.0
  - qutil=3.2.1
  - requests=2.22.0
  - retrying=1.3.3
  - s3transfer=0.3.2
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.3.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=45.1.0
  - six=1.14.0
  - smart_open=1.9.0
  - soupsieve=1.9.4
  - spacy=2.2.3
  - sqlite=3.30.1
  - srsly=1.0.0
  - statsmodels=0.11.0
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tensorflow-base=2.0.0
  - tensorflow-estimator=2.0.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - thinc=7.3.0
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.42.0
  - traitlets=4.3.3
  - urllib3=1.25.7
  - wasabi=0.6.0
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.34.0
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xarray=0.14.1
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zipp=2.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - gap-stat==1.7.1
    - gym==0.15.4
    - opencv-python==4.1.2.30
    - progressbar2==3.47.0
    - pygam==0.8.0
    - pyglet==1.3.2
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - python-utils==2.3.0
 